// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"iot-gateway/alarm"
	"iot-gateway/collector"
	"iot-gateway/configFile"
	"iot-gateway/controller"
	"iot-gateway/database/sqlite"
	"iot-gateway/push"
	"iot-gateway/router"
	"iot-gateway/service"
	"iot-gateway/workerPool"
	"runtime"
)

import (
	_ "embed"
	_ "iot-gateway/push/influxdb/v3"
	_ "iot-gateway/push/mqtt"
	_ "iot-gateway/push/tdengine/v3"
)

// Injectors from wire.go:

// InitializeApp 构建完整的应用依赖图
func InitializeApp() (*AppDependencies, func()) {
	config := configFile.InitConfig()
	db := sqlite.InitDB(config)
	userService := service.NewUserService(db)
	userController := controller.NewUserController(userService)
	workerPool := NewWorkerPool(config)
	engine := push.NewEngine(db)
	alarmEngine := alarm.NewEngine(db)
	collectorEngine := collector.NewEngine(db, workerPool, engine, alarmEngine)
	alarmService := service.NewAlarmService(db)
	deviceService := service.NewDeviceService(db, collectorEngine, alarmService)
	deviceController := controller.NewDeviceController(deviceService)
	deviceAddressService := service.NewDeviceAddressService(db)
	deviceAddressController := controller.NewDeviceAddressController(deviceAddressService)
	collectionService := service.NewCollectionService(collectorEngine)
	collectionController := controller.NewCollectionController(collectionService)
	protocolService := service.NewProtocolService(db)
	protocolController := controller.NewProtocolController(protocolService)
	pushChannelService := service.NewPushChannelService(db, alarmService)
	pushChannelController := controller.NewPushChannelController(pushChannelService)
	pushChannelFormService := service.NewPushChannelFormService(db)
	pushChannelFormController := controller.NewPushChannelFormController(pushChannelFormService)
	pushController := controller.NewPushController(engine)
	alarmController := controller.NewAlarmController(alarmService)
	logFileService := service.NewLogFileService(config)
	logFileController := controller.NewLogFileController(logFileService)
	v := ProvideRouteOptions(userController, deviceController, deviceAddressController, collectionController, protocolController, pushChannelController, pushChannelFormController, pushController, alarmController, logFileController)
	ginEngine := router.SetupRouter(v)
	channelMonitor := alarm.NewChannelMonitor(db, engine)
	appDependencies := &AppDependencies{
		Engine:          ginEngine,
		CollectorEngine: collectorEngine,
		PushEngine:      engine,
		AlarmMonitor:    channelMonitor,
	}
	return appDependencies, func() {
	}
}

// wire.go:

// AppDependencies 应用启动所需的所有依赖
type AppDependencies struct {
	Engine          *gin.Engine
	CollectorEngine *collector.Engine
	PushEngine      *push.Engine
	AlarmMonitor    *alarm.ChannelMonitor
}

// NewWorkerPool 从配置创建 Worker 池
func NewWorkerPool(cfg *configFile.Config) *workerPool.WorkerPool {
	pool := workerPool.NewWorkerPool(runtime.NumCPU()*2, 1024)
	pool.Start()
	return pool
}

// ProvideRouteOptions 组装所有领域路由选项，新增模块在此追加
func ProvideRouteOptions(
	uc *controller.UserController,
	dc *controller.DeviceController,
	ac *controller.DeviceAddressController,
	cc *controller.CollectionController,
	pc *controller.ProtocolController,
	pc2 *controller.PushChannelController,
	pcf *controller.PushChannelFormController,
	pus *controller.PushController,
	ac2 *controller.AlarmController,
	lc *controller.LogFileController,
) []router.RouteOption {
	return []router.RouteOption{router.WithUserRoutes(uc), router.WithDeviceRoutes(dc), router.WithDeviceAddressRoutes(ac), router.WithCollectionRoutes(cc), router.WithProtocolRoutes(pc), router.WithPushChannelRoutes(pc2), router.WithPushChannelFormRoutes(pcf), router.WithPushRoutes(pus), router.WithAlarmRoutes(ac2), router.WithLogFileRoutes(lc)}
}
